name: Bug Report
description: Report a bug in Queue Pilot
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure Queue Pilot with ...
        2. Run the tool ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true
  - type: dropdown
    id: broker
    attributes:
      label: Broker type
      options:
        - RabbitMQ
        - Kafka
        - Both
        - N/A
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Output of `node --version`
      placeholder: v22.x.x
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Queue Pilot version
      description: Output of `npx queue-pilot --version`
      placeholder: 0.5.0
    validations:
      required: false
